import Head from "next/head";
import React, { type ReactNode } from "react";
import { Inter } from "next/font/google";
import { useSession } from "next-auth/react";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

type Props = {
  children: ReactNode;
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const Layout = ({ children }: Props) => {
  const { status } = useSession();
  return (
    <>
      <Head>
        <title>Project Management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        key="1"
        className="grid max-h-screen w-full overflow-hidden lg:grid-cols-[280px_1fr]"
      >
        <Sidebar />
        <div className="flex h-screen flex-wrap">
          <Navbar />
          <main
            className={`font-sans ${inter.variable} h-[calc(100vh-60px)] w-full overflow-y-scroll bg-gradient-to-b from-[#2e026d]  to-[#15162c] p-4 p-4 md:p-6`}
          >
            {status === "loading" ? "Loading..." : children}
          </main>
        </div>
      </div>
    </>
  );
};

export default Layout;
